version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: SINA
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sina_db
    ports:
      - "5433:5432"
    volumes:
      # Mudança aqui: removemos o /data do final
      - data_sql:/var/lib/postgresql

volumes:
  data_sql: